name: evertec_challenge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  adaptive_theme: ^3.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  lottie: ^3.0.0
  intl: ^0.19.0
  bloc: ^8.1.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/flags/
    - assets/lottie/
    - assets/icons/
    - assets/imgs/
    - assets/json/