class FlagHelper {
  static getFlag(String state) {
    const map = {
      'AK': 'Alaska.png',
      'AL': 'Alabama.png',
      'AR': 'Arkansas.png',
      'AS': 'American_Samoa.png',
      'AZ': 'Arizona.png',
      'CA': 'California.png',
      'CO': 'Colorado.png',
      'CT': 'Connecticut.png',
      'DC': 'District_of_Columbia.png',
      'DE': 'Delaware.png',
      'FL': 'Florida.png',
      'GA': 'Georgia.png',
      'GU': 'Guam.png',
      'HI': 'Hawaii.png',
      'IA': 'Iowa.png',
      'ID': 'Idaho.png',
      'IL': 'Illinois.png',
      'IN': 'Indiana.png',
      'KS': 'Kansas.png',
      'KY': 'Kentucky.png',
      'LA': 'Louisiana.png',
      'MA': 'Massachusetts.png',
      'MD': 'Maryland.png',
      'ME': 'Maine.png',
      'MI': 'Michigan.png',
      'MN': 'Minnesota.png',
      'MO': 'Missouri.png',
      'MP': 'Northern_Mariana_Islands.png',
      'MS': 'Mississippi.png',
      'MT': 'Montana.png',
      'NC': 'North_Carolina.png',
      'ND': 'North_Dakota.png',
      'NE': 'Nebraska.png',
      'NH': 'New_Hampshire.png',
      'NJ': 'New_Jersey.png',
      'NM': 'New_Mexico.png',
      'NV': 'Nevada.png',
      'NY': 'New_York.png',
      'OH': 'Ohio.png',
      'OK': 'Oklahoma.png',
      'OR': 'Oregon.png',
      'PA': 'Pennsylvania.png',
      'PR': 'Puerto_Rico.png',
      'RI': 'Rhode_Island.png',
      'SC': 'South_Carolina.png',
      'SD': 'South_Dakota.png',
      'TN': 'Tennessee.png',
      'TX': 'Texas.png',
      'UT': 'Utah.png',
      'VA': 'Virginia.png',
      'VI': 'Us_Virgin_Islands.png',
      'VT': 'Vermont.png',
      'WA': 'Washington.png',
      'WI': 'Wisconsin.png',
      'WV': 'West_Virginia.png',
      'WY': 'Wyoming.png',
    };
    return map[state] ?? '';
  }
}
